name: Secret scanning

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # MUY IMPORTANTE para gitleaks

      - name: Build scanner image
        run: docker build -t cicd-security-scanner .

      - name: Run secret scanning
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/scan \
            cicd-security-scanner

      - name: Set date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload gitleaks report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: gitleaks-report-${{ steps.date.outputs.date }}
          path: reports/gitleaks.json

