name: Secret Scanning

on:
  pull_request:
    branches: [ "main" ]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Run scanner
        id: scanner
        uses: LauraWangQiu/cicd-security-scanner@v1
        with:
          base_ref: main
