name: Secret Scanning

on:
  pull_request:
    branches: [ "main" ]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Run scanner
        id: scanner
        uses: LauraWangQiu/cicd-security-scanner@v1
        with:
          base_ref: main

      - name: Upload artifact
        if: steps.scanner.outputs.secrets_found == 'true'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.sha }}
          path: reports/

      - name: Fail if secrets found
        if: steps.scanner.outputs.secrets_found == 'true'
        run: exit 1